# Generated by Django 5.1.4 on 2025-01-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=2083)),
            ],
        ),
    ]
